# Generated by Django 4.2.1 on 2023-06-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product category (e.g. Beverages)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('composition', models.TextField(help_text='Enter a product composition', max_length=1000)),
                ('ean', models.CharField(help_text='13 Character <a href="https://www.eancode.nl/wat-is-een-ean-code/">EAN code</a>', max_length=13, unique=True, verbose_name='EAN')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edostavka.productcategory')),
                ('manufacturer', models.ManyToManyField(help_text='Select a manufacturer for this product', to='edostavka.manufacturer')),
            ],
        ),
    ]
