# Generated by Django 4.2.1 on 2023-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edostavka', '0002_remove_product_category_remove_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=8),
            preserve_default=False,
        ),
    ]
